sonar.projectKey=guyinwonder168_clipper-agency
sonar.organization=guyinwonder168
sonar.projectName=clipper-agency
sonar.sources=clipper_agency/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/__init__.py
