name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - run: python3 -m pip install -r requirements.txt pytest pytest-cov

      - name: Run tests with coverage
        run: python3 -m pytest --cov=clipper_agency --cov-report=xml --cov-report=term

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@9c04cf17c9cc77780bde580c0aaa3d649a5303a6 # v4.2.0
        with:
          args: >
            -Dsonar.python.version=3.11
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
